insert into hotel (max_guests, name, price_per_night) values (5, 'hotel 1', 300);
insert into hotel (max_guests, name, price_per_night) values (2, 'hotel 2', 400);
insert into hotel (max_guests, name, price_per_night) values (3, 'hotel 3', 350);
insert into hotel (max_guests, name, price_per_night) values (1, 'foo', 600);
insert into hotel (max_guests, name, price_per_night) values (5, 'hotel 1', 300);
insert into hotel (max_guests, name, price_per_night) values (2, 'hotel 2', 400);
insert into hotel (max_guests, name, price_per_night) values (3, 'hotel 3', 350);
insert into hotel (max_guests, name, price_per_night) values (1, 'foo', 600);
insert into hotel (max_guests, name, price_per_night) values (5, 'hotel 1', 300);
insert into hotel (max_guests, name, price_per_night) values (2, 'hotel 2', 400);
insert into hotel (max_guests, name, price_per_night) values (3, 'hotel 3', 350);
insert into hotel (max_guests, name, price_per_night) values (1, 'foo', 600);

insert into address values (1, 'Warsaw', 'Poland', 'test street');
insert into address values (2, 'Cracow', 'Poland', 'test street');
insert into address values (3, 'Lodz', 'Poland', 'test street');
insert into address values (4, 'Wroclaw', 'Poland', 'test street');
insert into address values (5, 'Radom', 'Poland', 'test street');
insert into address values (6, 'Radomsko', 'Poland', 'test street');
insert into address values (7, 'Plock', 'Poland', 'test street');
insert into address values (8, 'Berlin', 'Germany', 'test street');
insert into address values (9, 'Warsaw', 'Poland', 'test street');
insert into address values (10, 'Cracow', 'Poland', 'test street');
insert into address values (11, 'Lodz', 'Poland', 'test street');
insert into address values (12, 'Wroclaw', 'Poland', 'test street');